# Generated by Django 4.0.3 on 2022-05-20 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del archivo')),
                ('filetype', models.CharField(max_length=4, verbose_name='Tipo de archivo')),
                ('path', models.URLField(max_length=500, verbose_name='Link del archivo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['pk'], 'verbose_name': 'Agencia'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['pk'], 'verbose_name': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='matter',
            options={'verbose_name': 'Asunto'},
        ),
        migrations.CreateModel(
            name='UserPqrsf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de documento')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo')),
                ('telephone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número telefónico')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número telefónico')),
                ('email', models.EmailField(blank=True, max_length=500, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=25, null=True, verbose_name='Dirección de residencia')),
                ('associate', models.BooleanField(blank=True, null=True, verbose_name='Asociado')),
                ('request_type', models.CharField(max_length=1, verbose_name='Tipo de petición')),
                ('medium', models.CharField(blank=True, max_length=1, null=True, verbose_name='Medio de respuesta')),
                ('description', models.TextField(max_length=1000, verbose_name='Descripción')),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('user_type', models.CharField(default='A', max_length=1, verbose_name='Tipo de usuario')),
                ('consumption', models.IntegerField(blank=True, null=True, verbose_name='Consumo')),
                ('token', models.CharField(blank=True, max_length=1280, null=True, verbose_name='Token')),
                ('ticket', models.CharField(max_length=16, verbose_name='Ticket')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.agency', verbose_name='Agencia')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='Ciudad')),
                ('files', models.ManyToManyField(blank=True, null=True, to='core.fileuser', verbose_name='Archivos del usuario')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matter', verbose_name='Asunto')),
            ],
        ),
    ]
